#!/usr/bin/env julia

function count_codons()
    data = open(readlines, "../data/codon_table.txt")
    numcodons = Dict()
    for line in data
        codons = matchall(r"[AUCG]{3}\s+(Stop|[A-Z]{1})", line)
        for pair in codons
            aa = split(pair)[2]
            aa in keys(numcodons) ? numcodons[aa] += 1 : numcodons[aa] = 1
        end
    end
    return numcodons
end

function modulo_reverse_translate(proteinseq::ASCIIString)
    numcodons = count_codons()
    poss_mrnas = 1
    for aa in split(proteinseq, "")
        poss_mrnas = (poss_mrnas*numcodons[aa])%1000000
    end
    poss_mrnas = (poss_mrnas*numcodons["Stop"])%1000000
    println(poss_mrnas%1000000)
end

function main()
    modulo_reverse_translate("MWYYVLPHHCRKPSTGIEWDEWNLLGNHCYNAKASRNFSDHDVITKEQDEAGHHVISKFQWQTNPLQQQIMNPTARKFIHHFACMYVSYDVTYGGPVQYLIWDPPNPDCNREHCQGQQCPQQHQFFHHKNSSDQPTNVDSDDVYHGYHRGCYRPRLCFGEEIAAAFTPSPCCLEYWATLPNFITAAQISKDMPEHGDLNDVFKPARRQTIGALHFFTCFYDPMWGCLVFNEIHLFMAYALLQPSHQNTGQPDELKGVNNLFWLCIWAWMTWGCMERYIEIRNWDMQFLCWMVLTLSHSCGYGYHGQWATPTWHLPISGDSCGYTQGPGNGHFRTFLNPHKKMVPNHKVWSESYIIMHDHSDFYPHNNKVRFNCRKNGYHPHLYIYLVLETMANEEFSCDWEYWFWKGSIAVVTMCCWCWINEDQELDAACWQHILEYDSYYLWRQDVFMCNVEMPCFAYKLLCWVTYHVPKGPFQLAANRRTPYRMPNNKHNTVIGRQERQKQQQDRQGTYLYDKTPDIPMFIQWPQISCCHPENANFGQSQVGCDDVMRFEYPMGSRSLVRCWMQNQQIGGSTFVAYEFCRMYMEKGNEYHYNHQRECSFRDNAGWGFRLIIWCTVWMMPQDMVHHRLLTVGLRAAIGTIDCNLTTADCLWKFMWLLSAFESIIISTKKEFQHSGGKYNEHYRQARQVAFNHCMYKSNDSQMVCHLHRPRIYSNRNSIDNSVYQLWCEWPLQQMETYKLPHLGRSATMCCIRGQRTHRHADMMSVQVCHAEKRRTTGCMVSLLDYALNFHSDDWTDFLATLYSAKIPQGRVPTKGARTVHTLQNCRPQNEFELYGGNEQRCSGMWAISEEMTEVQGFYVYSAFNWDTSFDDIRPVAWGQLNRIFRQQIHHQLFVDDKLAFCGGKMSGAVFVFHWLHIGLSTKNACIYCKIVPDGSCSITARHKQICYMNGQMIPIWHFSVAITLLLPPINKMDQVAMPEYTYFIFVAGPMMQHSTPRD")
end

main()

# $ ./reverse_translate.jl
# > 804288

