/*
 * Problem 2 - Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

// Recursive implementation of fibonacci sequence
int fibonacci(int n) {
    if (n <= 2) {
        return n;
    } else {
        return fibonacci(n - 1) + fibonacci(n - 2);
    }
}

// Non-recursive
int fibonacci2(int n) {
    int a = 1;
    int b = 1;
    int fib = 0;
    for (int i = 0; i < n; i++) {
        fib = a + b;
        a = b;
        b = fib;
    }
    printf("%d", fib);
    return 0;
}

int main(){
    fibonacci2(4);
    return 0;
}
